-- AlterTable
ALTER TABLE "images" ALTER COLUMN "image_1" DROP NOT NULL,
ALTER COLUMN "image_2" DROP NOT NULL,
ALTER COLUMN "image_3" DROP NOT NULL,
ALTER COLUMN "image_4" DROP NOT NULL,
ALTER COLUMN "image_5" DROP NOT NULL;
